version: "3.8"

services:
  nginx:
    container_name: "nginx_core"
    image: nginx # use official version
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
