version: "3.8"

services:
  prometheus:
    container_name: "prometheus_core"
    image: prom/prometheus # use official version
    ports:
      - 9090:9090   # Can skip if configuring backend in the same configuration file, to avoid exposure
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus # persist data even if container shuts down
      - prometheus_data:/prometheus
    networks:
      - my-network
    restart: unless-stopped

  grafana:
    container_name: "grafana_core"
    image: grafana/grafana # use official version
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources # persist data even if container shuts down
    networks:
      - my-network
    restart: unless-stopped

volumes:
  prometheus_data:  # named volumes can be managed easier using docker-compose

networks:
  my-network:
