# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker-compose-database/cassandra"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker-compose-database/dynamodb"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker-compose-database/mariadb"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker-compose-database/memcached"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker-compose-database/mongodb"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker-compose-database/mysql"
    schedule:
      interval: "weekly"
