version: "3.8"

services:
  rabbitmq:
    container_name: "rabbitmq_core"
    image: library/rabbitmq:management # use official version
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
#      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      - "rabbitmq_data:/data"
    networks:
      - my-network
    labels:
      NAME: "rabbitmq1"

volumes:
  rabbitmq_data:

networks:
  my-network:
