version: "3.8"

services:
  rabbitmq:
    container_name: "rabbitmq_core"
    image: rabbitmq:3.13.0-management-alpine # use official version
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - rabbitmq.env
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
#      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      - "rabbitmq_data:/data"
    networks:
      - my-network
    labels:
      NAME: "rabbitmq1"
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  my-network:
