version: "3.8"

services:
  cassandra:
    container_name: "cassandra_core_1"
    hostname: cassandra_core_1
    image: cassandra # use official version
    ports:
      - 9042:9042   # Expose native binary CQL port for your apps
    mem_limit: 2g   # It's not strictly required, but it's better to have some memory limit
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - ./data/cass1:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
#      - ./etc/cass1:/etc/cassandra   # Use your own config files for full control
    environment: &environment    # Declare and save environments variables into "environment"
      CASSANDRA_SEEDS: "cassandra_core_1"    # The first x nodes will be seeds (comma separated)
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: West
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    networks:
      - my-network
    restart: always

networks:
  my-network:
