version: "3.8"

services:
  pgbouncer:
    container_name: "pgbouncer_core"
    image: bitnami/pgbouncer:1.21.0 # use official version
    ports:
      - "6432:6432"   # Can skip if configuring backend in the same configuration file, to avoid exposure
    environment:
      - POSTGRESQL_HOST=postgresql
      - PGBOUNCER_AUTH_TYPE=trust
      - PGBOUNCER_CLIENT_TLS_SSLMODE=disable
    networks:
      - my-network
    restart: always

volumes:
  postgres_data:  # named volumes can be managed easier using docker-compose
    driver: local

networks:
  my-network:
