version: "3.8"

services:
  cassandra:
    container_name: cassandra_core
    hostname: cassandra_core_1
    image: cassandra # use official version
    ports:
      - "9042:9042"   # Expose native binary CQL port for your apps
#    cpus: '1.0'
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - ./data/cass1:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
#      - ./etc/cass1:/etc/cassandra   # Use your own config files for full control
    env_file:
      - cassandra.env
    networks:
      - my-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 1G
networks:
  my-network:
